services:
  - type: worker
    name: telegram-bot
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BAKONG_TOKEN
        sync: false
      - key: NEON_DATABASE_URL
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
